makeup/apps/dating/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView, LogoutView)
from .import views

app_name = 'dating'

urlpatterns = [
    path('', views.home, name='home'),
    path('signUp/', views.sign_up, name='SignUp'),
    path('login/', LoginView.as_view(template_name='dating/login.html'), name='login'),
    #path("after-login/", views.after_login_redirect, name="after_login_redirect"),
    path('logout/', LogoutView.as_view(template_name='dating/logout.html'), name='logout'),
    path('CreateProfile/', views.create_profile, name='create_profile'),
    path('updateProfile/', views.update_profile, name='update_profile'),
    #path('live/', views.go_live, name='live'),
    path('peopleLive/', views.see_live, name='see_live'),
    path('notifications/', views.notifications, name='notifications'),
    path('getProfile/<int:profile_id>/', views.get_profile, name='get_profile'),
    path('accept/<int:accept_id>', views.accept, name='accept'),
    path('reject/<int:reject_id>', views.reject, name='reject'),
    path('undo/<int:undo_id>', views.undo_reject, name='undo_reject'),
    path('LikerNotifications/',  views.LikerNotifications, name='LikerNotifications'),
    path('closeLikeNotification/',  views.closeLikeNotification, name='closeLikeNotification'),
    path('closeLikerNotification/',  views.closeLikerNotification, name='closeLikerNotification'),
    path('Contact-Us/',  views.contact_us, name='contact_us'),
    path('stopLive/',  views.stopLive, name='stopLive'),
    path('updateLocation/',  views.update_location, name='updateLocation'),
    path('likerHasProfile/',  views.liker_has_profile, name='likerHasProfile'),
    path('analytics/',  views.analytics, name='analytics')
]

makeup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('makeup.apps.dating.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

makeup/apps/dating/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class SignUpUser(AbstractUser):
    pass

    def __str__(self):
         return self.username


class Dating(models.Model):
    class Meta:
        verbose_name = ('Dating')
        verbose_name_plural = ('Dating')
        ordering = ['-text_status']

    text_status = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=200, blank=True)
    image = models.ImageField(upload_to='dating_images', blank=True)

    def __str__(self):
        return self.text_status


class OnlineMembers(models.Model):
    class Meta:
        verbose_name = ('OnlineMembers')
        verbose_name_plural = ('OnlineMembers')
        ordering = ['-id']

    id = models.IntegerField(primary_key=True)
    description = models.CharField(max_length=200, blank=True)
    data_to = models.BigIntegerField(default=0, null=False, blank=False)
    data_speed = models.BigIntegerField(default=0, null=False, blank=False)
    number = models.BigIntegerField(default=0, null=False, blank=False)

    def __str__(self):
        return self.description


class Profile(models.Model):
    class Meta:
        verbose_name = ('Profile')
        verbose_name_plural = ('Profile')
        ordering = ['-name']

    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    ]

    SKIN_TONE_CHOICES = [
        ('light', 'Light'),
        ('medium', 'Medium'),
        ('dark', 'Dark'),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)  # Added date of birth field
    color = models.CharField(max_length=10, choices=SKIN_TONE_CHOICES, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='profile_images', blank=True)
    contact = models.CharField(max_length=20, blank=True, null=True)
    consent = models.BooleanField(default=False)

    def __str__(self):
        return self.name if self.name else "Unnamed Profile"

    def calculate_age(self):
        from datetime import date
        today = date.today()
        age = today.year - self.dob.year
        if today.month < self.dob.month or (today.month == self.dob.month and today.day < self.dob.day):
            age -= 1
        return age

# class LiveUser(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     profile = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True)  # Reference to Profile
#     is_live = models.BooleanField(default=False)  # Indicates if user is live
#     latitude = models.FloatField(null=True, blank=True)  # Store latitude
#     longitude = models.FloatField(null=True, blank=True)  # Store longitude
#
#     def __str__(self):
#         return f"{self.user.username} (Live: {self.is_live})"

class LiveUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True)  # Reference to Profile
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    last_active = models.DateTimeField(auto_now=True)  # Track when user was last online
    is_live = models.BooleanField(default=True)  # Track if user is online

    def __str__(self):
        return f"{self.user.username} (Last Active: {self.last_active})"

class LikeNotification(models.Model):
    liker = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_likes', on_delete=models.CASCADE)
    liked_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_likes', on_delete=models.CASCADE)
    message = models.CharField(max_length=500, null=True, blank=True)
    status = models.CharField(max_length=20, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending')
    closed_by_liked_user = models.BooleanField(default=False)  # Closed by liked user
    closed_by_liker = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f"{self.liker} liked {self.liked_user}"


class Contact(models.Model):
     class Meta:
         verbose_name_plural = ('Contact')
         ordering = ['id']

     name = models.CharField(max_length=50, blank=True)
     email = models.EmailField(max_length=254)
     message = models.TextField(max_length=500, blank=True)

     def __str__(self):
         return self.name

makeup/apps/dating/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import SignUpUser

class SignUpCreationForm(UserCreationForm):
    class Meta:
        model = SignUpUser
        fields = ('username', 'password1', 'password2')
        label_suffix = ''

    def __init__(self, *args, **kwargs):
        super(SignUpCreationForm, self).__init__(*args, **kwargs)
        # Add a placeholder for the username field with an example
        self.fields['username'].widget.attrs.update({
            'placeholder': 'e.g., user123, john_doe'
        })

    def save(self, commit=True):
        user = super().save(commit=False)
        # user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

makeup/apps/dating/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login
from .forms import SignUpCreationForm
from .models import Dating, OnlineMembers, Contact, SignUpUser, Profile,LikeNotification, LiveUser
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import datetime
import random
from django.core.exceptions import ValidationError
import re
from django.utils import timezone
from django.template.defaultfilters import timesince
from django.utils import timezone
from django.shortcuts import render, redirect
import plotly.graph_objs as go
from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.utils.timezone import now
from datetime import timedelta
from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from django.core.serializers.json import DjangoJSONEncoder


class CustomJSONEncoder(DjangoJSONEncoder):
    """Custom encoder to handle datetime and other special cases."""
    def default(self, obj):
        if hasattr(obj, 'isoformat'):
            return obj.isoformat()
        return super().default(obj)

def calculate_age(dob):
    today = datetime.today().date()
    age = today.year - dob.year
    if today.month < dob.month or (today.month == dob.month and today.day < dob.day):
        age -= 1
    return age


def home(request):
    dating = Dating.objects.all()
    members = OnlineMembers.objects.all()

    user = request.user

    # Ensure user is authenticated
    if not user.is_authenticated:
        messages.error(request, "You must be logged in to access this page.")
        return redirect("dating:login")  # Redirect to login page if user is not authenticated

    # Ensure user has a profile
    profile = getattr(user, "profile", None)
    if profile is None:
        messages.warning(request, ".Set up your profile to continue")
        return redirect("dating:create_profile")

    # Update or create LiveUser entry
    live_user, created = LiveUser.objects.update_or_create(
        user=user,
        defaults={"is_live": True, "profile": profile}
    )

    live_user, created = LiveUser.objects.get_or_create(user=request.user)

    # If the user is live, set their status (you might want to do this)
    if not live_user.is_live:
        live_user.is_live = True
        live_user.save()

    # Fetch all live users (including the current user)
    live_users = LiveUser.objects.filter(is_live=True)

    live_users_data = []

    # Define default coordinates (center of the city, for example)
    DEFAULT_LAT = 0.3349217  # Replace with a suitable default latitude
    DEFAULT_LNG = 32.6033867  # Replace with a suitable default longitude

    # Process each live user
    existing_coordinates = set()  # Track used coordinates

    for live in live_users:
        profile = live.profile
        if profile:
            age = calculate_age(profile.dob)
            latitude = live.latitude if live.latitude is not None else DEFAULT_LAT
            longitude = live.longitude if live.longitude is not None else DEFAULT_LNG

            # If the coordinates are already used, adjust them slightly
            while (latitude, longitude) in existing_coordinates:
                latitude += 0.00001  # Tiny shift to separate markers
                longitude += 0.00001

            existing_coordinates.add((latitude, longitude))  # Store new coordinates

            live_users_data.append({
                'id': profile.id,
                'name': getattr(profile, 'name', 'Unknown'),
                'gender': profile.gender,
                'bio': profile.bio,
                'color': profile.color,
                'latitude': latitude,
                'longitude': longitude,
                'image': getattr(profile.image, 'url', ''),
                'age': age
            })

    # Try to access the current user's profile
    try:
        profile = request.user.profile
    except ObjectDoesNotExist:
        profile = None  # Set profile to None if it doesn't exist

    # Pass the necessary data to the context
    context = {
        'live_users_data': live_users_data,
        'current_user_live': live_user.is_live,
        'current_user_id': request.user.id,
        'profile': profile  # Pass the user's profile if it exists, or None
    }

    print(live_users_data)

    # Render template with live users' data
    return render(request, "dating/index.html", context)


def sign_up(request):
    if request.method == 'POST':
        form = SignUpCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('dating:login')  # Redirect to login page or any other page
    else:
        form = SignUpCreationForm()

    return render(request, 'dating/sign_up.html', {'form': form})



@login_required
def create_profile(request):
    # Function to validate the contact number (for WhatsApp)
    def validate_contact(contact):
        # Regex pattern for validating phone numbers without spaces
        pattern = r"^\+(\d{1,4})(\d{6,14})$"  # No spaces allowed
        if not re.match(pattern, contact):
            raise ValidationError("Invalid phone number format. Please use the format: +<country_code><number> (e.g., +256712345678).")

    # Check if the user already has a profile
    try:
        profile = Profile.objects.get(user=request.user)
        # If the profile exists, update it
        if request.method == 'POST':
            # Get data from the form
            name = request.POST.get('name')
            gender = request.POST.get('gender')
            dob = request.POST.get('dob')
            color = request.POST.get('color')
            bio = request.POST.get('bio')
            image = request.FILES.get('photo')
            contact = request.POST.get('contact')
            consent = request.POST.get('consent') == 'on'

            # Validate the contact number format
            validate_contact(contact)

            # Convert the dob string to a DateField format
            dob = datetime.strptime(dob, '%Y-%m-%d').date()

            # Update the existing profile
            profile.name = name
            profile.gender = gender
            profile.dob = dob
            profile.color = color
            profile.bio = bio
            profile.image = image
            profile.contact = contact
            profile.consent = consent
            profile.save()

            # Update the LiveUser instance to link to the updated profile
            #live_user, created = LiveUser.objects.get_or_create(user=request.user)
            #live_user.profile = profile  # Set the profile
            #live_user.save()  # Save the changes to LiveUser

            return redirect('dating:home')  # Redirect after profile update

    except Profile.DoesNotExist:
        # If the user doesn't have a profile, create a new one
        if request.method == 'POST':
            name = request.POST.get('name')
            gender = request.POST.get('gender')
            dob = request.POST.get('dob')
            color = request.POST.get('color')
            bio = request.POST.get('bio')
            image = request.FILES.get('photo')
            contact = request.POST.get('contact')
            consent = request.POST.get('consent') == 'on'

            # Validate the contact number format
            validate_contact(contact)

            # Convert the dob string to a DateField format
            dob = datetime.strptime(dob, '%Y-%m-%d').date()

            # Create a new profile
            profile = Profile.objects.create(
                user=request.user,
                name=name,
                gender=gender,
                dob=dob,
                color=color,
                bio=bio,
                image=image,
                contact=contact,
                consent=consent,
            )

            # Update the LiveUser instance to link to the new profile
            #live_user, created = LiveUser.objects.get_or_create(user=request.user)
            #live_user.profile = profile  # Set the profile
            #live_user.save()  # Save the changes to LiveUser

            return redirect('dating:home')  # Redirect after profile creation


    return render(request, 'dating/create_profile.html')

@login_required
def update_profile(request):
    profile = Profile.objects.get(user=request.user)  # Get the logged-in user's profile

    if request.method == 'POST':
        name = request.POST.get('name')
        gender = request.POST.get('gender')
        dob = request.POST.get('dob')
        color = request.POST.get('color')
        bio = request.POST.get('bio')
        contact = request.POST.get('contact')
        consent = request.POST.get('consent') == 'on'

        image = request.FILES.get('photo')  # Get uploaded image

        # Convert DOB to date format
        if dob:
            dob = datetime.strptime(dob, '%Y-%m-%d').date()

        # Update profile fields
        profile.name = name
        profile.gender = gender
        profile.dob = dob
        profile.color = color
        profile.bio = bio
        profile.contact = contact
        profile.consent = consent

        # Only update the image if a new one was uploaded
        if image:
            profile.image = image

        profile.save()

        return redirect('dating:home')  # Redirect after successful update

    return render(request, 'dating/update_profile.html', {"profile": profile})



# @login_required
# def go_live(request):
#     user = request.user
#

makeup/apps/dating/templates/dating/get_profile.html
<h6><strong>Profile Details</strong></h6>

<div class="profile">
<p><img src="{{ profile.image.url }}" alt="{{ profile.name }}'s profile picture" style="width: 80px; height: 90px;"></p>
<p><strong>Name:</strong> {{ profile.name }}</p>
<p><strong>Gender:</strong> {{ profile.gender }}</p>
<p><strong>Height:</strong> {{ profile.height }} cm</p>
<p><strong>Weight:</strong> {{ profile.weight }} kg</p>
<p><strong>Skin Tone:</strong> {{ profile.color }}</p>
<p><strong>Bio:</strong> {{ profile.bio }}</p>
</div>

makeup/apps/dating/templates/dating/go_live.html
{% extends 'base_dating.html' %}
    {% load static %}

{% block links %}
<!-- font awesome -->


<link href="{% static 'css/live.css' %}" rel="stylesheet" type="text/css" />

<!--<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" />-->
{% endblock links %}


 {% block nav %}
<!--  <ul class="menu-links" style="display: none; max-height: 400px; overflow: auto;">-->
<!--          <li class="hoverTrigger"><a  id="stopLiveButton" onclick="handleUserLeaveLive()">Stop Live</a></li>-->
<!--&lt;!&ndash;          <li class="hoverTrigger"><a href="{% url 'dating:home' %}">Home</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;         <li class="hoverTrigger"><a href="#"></a></li>&ndash;&gt;-->
<!--   </ul>-->


{% endblock nav %}


{% block body %}
 <p class="status"></p>
<!-- Notification Popup (Toast Style) -->
<div id="liveNotification">
  You are live now
</div>

<!-- Modal Structure -->
<div id="imageModal" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.8); justify-content: center; align-items: center; z-index: 1000;">
    <span style="position: absolute; top: 20px; right: 20px; color: #fff; font-size: 35px; cursor: pointer;" onclick="closeModal()">&times;</span>
    <img id="modalImage" style="max-width: 40%; max-height: 50%; border-radius: 10px;">
</div>

<div id="noLongerLiveNotification" style="display: none; position: fixed; top: 50px; left: 700px; background-color: #f44336; color: white; padding: 15px; border-radius: 5px; z-index: 1000;">
    You are no longer live
</div>


{% endblock body %}

{% block foot %}
<div class="map-container">
    <div id="map"></div>
</div>
{% endblock foot %}

{% block scripts %}
<script src="https://maps.googleapis.com/maps/api/js?address=8HRV+8P8&key=AIzaSyCqpezCVAMRqrF3jzjZB6mQWfuB1sfz-2I&callback=initMap" async defer></script>

<!--<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCqpezCVAMRqrF3jzjZB6mQWfuB1sfz-2I&libraries=marker&callback=initMap"
    defer
></script>-->
<!--<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"></script>-->
<script type="text/javascript" src="{% static 'js/go_live.js' %}"></script>
<script type="text/javascript">
     window.userData = {
            id: "{{ user_id }}",
            image: "{{ profile.image.url|escapejs }}",
            name: "{{ profile.name|escapejs }}",
            gender: "{{ profile.gender|escapejs }}",
            bio: "{{ profile.bio|escapejs }}",
            height: "{{ profile.height|escapejs }}",
            weight: "{{ profile.weight|escapejs }}",
            is_live: {{ current_user_live|yesno:"true,false" }},
        };

        window.currentUserId = "{{ current_user_id }}";
        window.liveUsersData = {{ live_users_data|safe }};
</script>
<script>
    const stopLive = "{% url 'dating:stopLive' %}";
    const updateLocation = "{% url 'dating:updateLocation' %}";

</script>
<script type="text/javascript" src="{% static 'js/js.cookie.min.js' %}"></script>
<script type="text/javascript">

     var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
              // these HTTP methods do not require CSRF protection
              return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
              }
            });

  $(document).ready(function () {


     {% block domready %}
     {% endblock %}
  });
    </script>

<!--<script type="text/javascript" src="{% static 'js/live1.js' %}"></script>-->
{% endblock scripts %}

makeup/apps/dating/templates/dating/index.html
{% extends 'base_dating.html' %}

makeup/apps/dating/templates/dating/notifications.html
{% extends 'base_dating.html' %}
{% load static %}
{% load tz %}



{% block links %}
<link href="{% static 'css/notifications1.css' %}" rel="stylesheet" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>



{% endblock links %}



{% block nav %}
<!--<ul class="menu-links" style="display: none; max-height: 400px; overflow: auto;">-->
<!--    <li class="hoverTrigger"><a href="{% url 'dating:home' %}"> Home</a> </li>-->
<!-- </ul>-->
{% endblock nav %}

{% block body %}
{% endblock body %}

{% block foot %}

<div class="notifications-container">
   <h3 style="font-weight:bold">Notifications</h3>
<ul class="notifications-list">
    {% for user in liked_users %}
        <li class="notification-item" data-notification-id="{{ user.id }}" data-status="{{ user.status }}">
            <img src="{{ user.liker.profile.image.url }}" alt="{{ user.liker.username }}" class="notification-avatar">
            <div class="notification-content">
<!--             <h6 class="notification-text">-->
<!--              !Good news! <span class="username">{{ user.liker.username|capfirst }}</span> wants to connect-->
<!--            </h6>-->
             <h6 class="notification-text">
             .Connection request from <span class="username">{{ user.liker.username|capfirst }}</span>
            </h6>


               <p class="notification-time" data-timestamp="{{ user.timestamp|date:'c' }}"></p>

<!--                <div class="notifications-actions">-->
<!--                    {% if user.status == 'accepted' %}-->
<!--                        <span class="action-link accept">Accepted</span>-->
<!--                    {% elif user.status == 'rejected' %}-->
<!--                        <span class="action-link reject">Rejected</span>-->
<!--                    {% else %}-->
<!--                        <a class="action-link accept" href="#" data-liker-id="{{ user.liker.id }}" acceptUrl="{% url 'dating:accept' user.liker.id %}">Accept</a>-->
<!--                        <a class="action-link reject" href="#" data-liker-id="{{ user.liker.id }}" rejectUrl="{% url 'dating:reject' user.liker.id %}">Reject</a>-->
<!--                    {% endif %}-->
<!--                    <a class="action-link view-profile" href="#" data-user-id="{{ user.liker.profile.id }}" getProfileUrl="{% url 'dating:get_profile' user.liker.profile.id %}">View Profile</a>-->
                  <div class="notification-actions">
                        {% if user.status == 'accepted' %}
                            <!-- Show 'Accept' button, hide 'Reject' but keep space -->
                             <button class="action-link accept" data-tooltip="Accepted" disabled>
                                    <i class="fas fa-check bold-checkmark"></i>
                             </button>
                             <button class="action-link reject hidden-button" disabled>
                                <i class="fas fa-times"></i>
                            </button>
                        {% elif user.status == 'rejected' %}
                            <!-- Show 'Reject' button, hide 'Accept' but keep space -->
                               <button class="action-link reject" data-tooltip="Rejected" disabled>
                                <i class="fas fa-times"></i>
                            </button>

                             <button class="action-link accept hidden-button" data-tooltip="Accepted" disabled>
                                    <i class="fas fa-check bold-checkmark"></i>
                             </button>



                        {% else %}
                            <!-- Show both buttons if no status -->
                            <button class="action-link reject"
                                data-tooltip="Reject"
                                data-liker-id="{{ user.liker.id }}"
                                rejectUrl="{% url 'dating:reject' user.liker.id %}">
                                <i class="fas fa-times"></i>
                            </button>
                            <button class="action-link accept"
                                data-tooltip="Accept"
                                data-liker-id="{{ user.liker.id }}"
                                acceptUrl="{% url 'dating:accept' user.liker.id %}">
                                <i class="fas fa-check"></i>
                            </button>
                        {% endif %}
                        <!-- Always show 'View Profile' button -->
                        <button class="action-link view-profile"
                            data-user-id="{{ user.liker.profile.id }}"
                            getProfileUrl="{% url 'dating:get_profile' user.liker.profile.id %}"
                            data-tooltip="View Profile">
                            <i class="fas fa-user"></i>
                        </button>
                      <!-- Example Button and Tooltip -->
                    </div>


<!--                </div>-->
<!--            </div>-->
            <button class="close-notification" id="closeBtn">x</button>
            </div>
        </li>
    {% empty %}
        <li>No notifications</li>
    {% endfor %}
</ul>


<ul class="notifications-list">
    <!-- Notifications for the liker -->
    {% for notification in liker_notifications %}
    <li class="notification-item" data-notification-id="{{ notification.id }}" data-status="{{ notification.status }}">
        <img src="{{ notification.liked_user.profile.image.url }}" alt="{{ notification.liked_user.username }}" class="notification-avatar">
        <div class="notification-contents">
            <div class="notification-messages">
                {% if notification.status == "accepted" %}
                    <h6><span class="username1">.{{ notification.liked_user.username|capfirst }}</span> said yes to connecting</h6>
                {% else %}
                    <h6><span class="username2">.{{ notification.liked_user.username|capfirst }}</span> declined your like</h6>
                {% endif %}
            </div>

            <div class="likerNotes">
                 <p class="notification-time" data-timestamp="{{ notification.timestamp|date:'c' }}"></p>



              <p style="color:black; margin-top:20px">
                    {% if notification.status == "accepted" %}
                        {% if notification.liked_user.profile and notification.liked_user.profile.contact %}
                <a href="https://wa.me/{{ notification.liked_user.profile.contact }}"
                    target="_blank"
                    style="text-decoration: none; color: inherit; margin-right:170px; margin-top:20px">
                    {{ notification.liked_user.profile.contact|slice:"1:" }}+
                    <i class="fab fa-whatsapp" style="color: #25D366; font-size: 23px"></i>
                </a>
                        {% else %}
                            <p style="margin-right:142px; color:black">Contact: Not available</p>
                        {% endif %}
                    {% else %}
                        <p  style="margin-right:142px; color:black">Contact: Not available</p>
                    {% endif %}
                </p>
             </div>
            <button class="close-notifications" id="liker-notifications-{{ notification.id }}">x</button>

        </div>
    </li>
    {% empty %}
    <p>No updates on your likes.</p>
    {% endfor %}
</ul>



</div>


<!-- Modal Structure -->
<div id="profileModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <div id="profileDetails">
            <!-- Profile details will be dynamically loaded here -->
        </div>
    </div>
</div>

<!-- Toast Notification -->
<div id="accept-toast" class="toast">
    <span class="toast-message">You accepted the like!</span>
</div>
{% endblock foot %}

{% block scripts %}
<script>
    const undoRejectUrlTemplate = "{% url 'dating:undo_reject' '0' %}"; // Use a placeholder
    const closeLikeNotification = "{% url 'dating:closeLikeNotification' %}";
</script>




<script type="text/javascript" src="{% static 'js/notifications.js' %}"></script>
<script type="text/javascript" src="{% static 'js/js.cookie.min.js' %}"></script>
<script type="text/javascript">

     var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
              // these HTTP methods do not require CSRF protection
              return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
              beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
              }
            });

  $(document).ready(function () {


     {% block domready %}
     {% endblock %}
  });
    </script>
{% endblock scripts %}